### ISSUE TITLE
Chuffed ignores alldifferent on large domain variables

### ISSUE THREAD

**Issue by GustavBjordal** [chuffed/chuffed#46] opened 2019-09-04 08:13 UTC
This is most likely related to issue #10 which is about chuffed ignoring alldiff on unbound (var int) variables.

In the following golumb ruler model chuffed gives the solution
```
 ruler = array1d(1..7, [0, 0, 0, 0, 0, 0, 0]);
----------
==========
```
despite the `alldifferent(ruler)`. 

The bug seems to be for all `n >= 7` and the model works fine for smaller `n`.

```
include "globals.mzn";
int: n = 7;

array[1..n] of var 0..sum(1..n*n): ruler; % this, not so good, upperbound seems to trigger the bug.

constraint alldifferent(ruler);
constraint increasing(ruler); % this constraint has no impact on the bug
constraint alldifferent([abs(ruler[i]-ruler[j]) | i, j in 1..n where i < j]);

solve minimize ruler[n];
```

**Comment by Dekker1** [comment] 2023-01-20 02:55
Confirmed to be a duplicate of #10

**Closed by Dekker1** 2023-01-20 02:55 UTC
