### ISSUE TITLE
Examples do not compile

### ISSUE THREAD

**Issue by nnarodytska** [chuffed/chuffed#4] opened 2017-06-11 22:16 UTC
Hi All,

I complied Chuffed on Ubuntu 16.04. However, when I tried to compile examples  I got the following error message (please see below). Any advice will  be very much appreciated.

> [ 64%] Linking CXX static library libchuffed.a
[ 64%] Built target chuffed
[ 65%] Generating lexer.yy.cpp
[ 66%] Generating parser.tab.cpp, chuffed/flatzinc/parser.tab.h
Scanning dependencies of target chuffed_fzn
[ 66%] Building CXX object CMakeFiles/chuffed_fzn.dir/parser.tab.cpp.o
[ 67%] Building CXX object CMakeFiles/chuffed_fzn.dir/chuffed/flatzinc/registry.cpp.o
[ 68%] Building CXX object CMakeFiles/chuffed_fzn.dir/chuffed/flatzinc/flatzinc.cpp.o
[ 69%] Building CXX object CMakeFiles/chuffed_fzn.dir/lexer.yy.cpp.o
[ 69%] Linking CXX static library libchuffed_fzn.a
[ 69%] Built target chuffed_fzn
Scanning dependencies of target rcpsp
[ 69%] Building CXX object CMakeFiles/rcpsp.dir/chuffed/examples/rcpsp.cpp.o
[ 70%] Linking CXX executable rcpsp
libchuffed.a(engine.cpp.o): In function `Engine::search(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
engine.cpp:(.text+0x2c07): undefined reference to `typeinfo for FlatZinc::FlatZincSpace'
engine.cpp:(.text+0x2c68): undefined reference to `FlatZinc::FlatZincSpace::printDomains(std::ostream&)'
engine.cpp:(.text+0x2f0e): undefined reference to `typeinfo for FlatZinc::FlatZincSpace'
engine.cpp:(.text+0x2f45): undefined reference to `FlatZinc::FlatZincSpace::getDomainsString[abi:cxx11]()'
collect2: error: ld returned 1 exit status
CMakeFiles/rcpsp.dir/build.make:96: recipe for target 'rcpsp' failed
make[3]: *** [rcpsp] Error 1
CMakeFiles/Makefile2:892: recipe for target 'CMakeFiles/rcpsp.dir/all' failed
make[2]: *** [CMakeFiles/rcpsp.dir/all] Error 2
CMakeFiles/Makefile2:668: recipe for target 'CMakeFiles/examples.dir/rule' failed
make[1]: *** [CMakeFiles/examples.dir/rule] Error 2
Makefile:383: recipe for target 'examples' failed
make: *** [examples] Error 2

------------
Thanks!

nina

**Comment by PatrickTrentin88** [comment] 2017-09-19 10:29
The same issue is reproducible on Ubuntu 17.04, `gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)`

**Comment by schutta** [comment] 2017-11-15 03:30
The issue is fixed in the develop branch and was related to the dynamic_cast from base to derived class, which requires function definitions of functions used after the cast in the derived class declaration.

**Closed** 2018-08-09 03:43 UTC
