### ISSUE TITLE
Introduce Support for `indomain_random` in Solver Annotations

### ISSUE THREAD

**Issue by MatteoFasulo** [chuffed/chuffed#194] opened 2024-05-30 17:13 UTC
## Description:
Hello,

I am writing to request help with introducing the support for `indomain_random` in solver annotations for the Chuffed solver.

### Issue:

Currently, the Chuffed solver does not support the `indomain_random` annotation. This limits the flexibility and potential performance of the solver in certain scenarios.

Thank you for your time and consideration.

**Comment by schutta** [comment] 2024-05-31 00:09
I close this issue, because it is a duplicate of the issue #122 .

**Closed as completed by schutta** 2024-05-31 00:09 UTC
Labels: enhancement
